//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFramework.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> Sex { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> LastTimeLogin { get; set; }
        public int Status { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.Guid> GroupRoleID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateBy { get; set; }
    }
}
