//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFramework.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseDBEntities : DbContext
    {
        public BaseDBEntities()
            : base("name=BaseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNT { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<CONTROL> CONTROL { get; set; }
        public virtual DbSet<GROUP_ROLE> GROUP_ROLE { get; set; }

        public System.Data.Entity.DbSet<NetFramework.Models.DTO.MenuDTO> MenuDTOes { get; set; }
    }
}
