//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFramework.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        public System.Guid ID { get; set; }
        public System.Guid AccountID { get; set; }
        public System.Guid ItemID { get; set; }
        public Nullable<System.Guid> GruopRoleID { get; set; }
    }
}
